// <auto-generated />
namespace HMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class identityFrameworkreference : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identityFrameworkreference));
        
        string IMigrationMetadata.Id
        {
            get { return "202309050858210_identityFrameworkreference"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
